-- ==============================================================================
-- EARLY STUDENT SUPPORT SYSTEM (ESS) - SUPABASE POSTGRESQL SCHEMA
-- ==============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS departments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  code TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  role TEXT CHECK (role IN ('admin', 'faculty', 'counselor')) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  department_id BIGINT REFERENCES departments(id) ON DELETE SET NULL,
  year INT NOT NULL CHECK (year BETWEEN 1 AND 5),
  enrollment_date DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  status TEXT CHECK (status IN ('present', 'absent', 'late')) NOT NULL,
  subject TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS academic_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
  course TEXT NOT NULL,
  score DECIMAL(5,2) NOT NULL CHECK (score >= 0 AND score <= 100),
  date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS engagement (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
  lms_logins INT NOT NULL DEFAULT 0,
  assignments_submitted INT NOT NULL DEFAULT 0,
  time_on_task INT NOT NULL DEFAULT 0,
  date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS risk_assessments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
  risk_score DECIMAL(3,2) NOT NULL CHECK (risk_score >= 0.00 AND risk_score <= 1.00),
  tier TEXT CHECK (tier IN ('GREEN', 'AMBER', 'RED', 'CRITICAL')) NOT NULL,
  trajectory TEXT CHECK (trajectory IN ('improving', 'stable', 'deteriorating')) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS root_cause_assessments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
  primary_cause TEXT NOT NULL,
  confidence INT NOT NULL CHECK (confidence >= 0 AND confidence <= 100),
  factors TEXT[] DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS interventions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  status TEXT CHECK (status IN ('recommended', 'pending', 'assigned', 'in_progress', 'completed')) NOT NULL DEFAULT 'recommended',
  assigned_to BIGINT REFERENCES users(id) ON DELETE SET NULL,
  due_date DATE,
  outcome TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_students_dept ON students(department_id);
CREATE INDEX IF NOT EXISTS idx_attendance_student_date ON attendance(student_id, date);
CREATE INDEX IF NOT EXISTS idx_academics_student_date ON academic_records(student_id, date);
CREATE INDEX IF NOT EXISTS idx_engagement_student_date ON engagement(student_id, date);
CREATE INDEX IF NOT EXISTS idx_risk_student_tier ON risk_assessments(student_id, tier);
CREATE INDEX IF NOT EXISTS idx_interventions_student_status ON interventions(student_id, status);

INSERT INTO users (id, email, role, created_at) VALUES
  (1, 'admin@college.edu', 'admin', NOW()),
  (2, 'faculty@college.edu', 'faculty', NOW()),
  (3, 'counselor@college.edu', 'counselor', NOW())
ON CONFLICT (email) DO UPDATE SET role = EXCLUDED.role;
